{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ML Service CPU use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "keazy_backend_process_cpu_seconds_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ML Service Mem use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "keazy_backend_process_resident_memory_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mongodb_sys_netstat_Tcp_CurrEstab{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload Hitting ML Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "mongodb_top_commands_count{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Loki logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"keazy-backend\"}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "mongodb_sys_vmstat_pgfault{}", "legendFormat": "__auto" }
   ]
  }
 ]
}